# Generated by Django 4.2.6 on 2023-11-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condenser_unit_serial', models.CharField(blank=True, max_length=250, null=True)),
                ('condenser_material_code', models.CharField(blank=True, max_length=250, null=True)),
                ('condenser_status_test', models.BooleanField(blank=True, default=False, null=True)),
                ('compressor_unit_serial', models.CharField(blank=True, max_length=250, null=True)),
                ('compressor_material_code', models.CharField(blank=True, max_length=250, null=True)),
                ('compressor_status_test', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
