# Generated by Django 4.2.6 on 2023-11-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='compressor_status_test',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
