# Generated by Django 4.2.6 on 2023-11-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_alter_component_compressor_status_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='compressor_status_test',
        ),
    ]
