# Generated by Django 4.2.6 on 2023-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_remove_component_compressor_status_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='compressor_unit_serial',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='condenser_unit_serial',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
