# Generated by Django 4.2.6 on 2024-03-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_component_compressor_unit_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='order',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
