# Generated by Django 4.2.6 on 2023-10-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=32)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_closed', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condenser_unit_serial', models.CharField(max_length=250)),
                ('condenser_material_code', models.CharField(max_length=250)),
                ('compressor_unit_serial', models.CharField(max_length=250)),
                ('compressor_material_code', models.CharField(max_length=250)),
                ('material_type', models.CharField(blank=True, max_length=10, null=True)),
                ('send_to_sap', models.BooleanField(default=False)),
                ('sap_status', models.CharField(blank=True, max_length=250, null=True)),
                ('serie', models.CharField(blank=True, max_length=250, null=True)),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pallets.pallet')),
            ],
        ),
    ]
