# Generated by Django 4.2.6 on 2023-10-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='identifier',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
