# Generated by Django 4.2.6 on 2023-11-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0002_alter_pallet_identifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='MountedComponent',
        ),
    ]
