# Generated by Django 4.2.6 on 2023-11-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0003_rename_component_mountedcomponent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mountedcomponent',
            name='sap_status',
        ),
        migrations.RemoveField(
            model_name='mountedcomponent',
            name='send_to_sap',
        ),
        migrations.RemoveField(
            model_name='mountedcomponent',
            name='serie',
        ),
        migrations.AddField(
            model_name='pallet',
            name='fase',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='sap_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='send_to_sap',
            field=models.BooleanField(default=False),
        ),
    ]
