# Generated by Django 4.2.6 on 2023-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallets', '0005_pallet_sap_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountedcomponent',
            name='sap_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountedcomponent',
            name='send_to_sap',
            field=models.BooleanField(default=False),
        ),
    ]
